name: My First Workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: welcome message
          run: |
            echo "My first Github Actions Job"
            ls -ltra
            cat README.md

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt


        # editing to put these two codes on the last line below.
          # - name: List files
        #   run: ls

        # - name: Read file
        #   run: cat README.md
